package PResoluciones;


import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;


public class ElegirResolucion extends javax.swing.JFrame implements ActionListener {

    ArrayList<String> resoluciones;
    private final JButton[] botones;
    private final JButton btnSalir;
    private final JLabel tittle;
    public String resolucionActual; 

    public ElegirResolucion() {
        initComponents();
        this.resoluciones = ResolucionDatos.leerArchivo();
        setSize(800, 700);
        botones = new JButton[resoluciones.size()];
        tittle = new JLabel();
        tittle.setText("Elige la resolucion");
        tittle.setFont(new java.awt.Font("Times New Roman", 1, 20));
        tittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        
        getContentPane().add(tittle);
        getContentPane().setLayout(new GridLayout((getWidth()/100),(getWidth()/100)));
        int i;
        for (i = 0; i < resoluciones.size(); i++) {
            botones[i] = new JButton(resoluciones.get(i));
            getContentPane().add(botones[i]);
            botones[i].addActionListener(this);
        }
        
       btnSalir = new JButton("salir");
       btnSalir.setBounds((getHeight()/2),(getWidth()/2),120,30);
       btnSalir.addActionListener(this); 
       getContentPane().add(btnSalir);
       addWindowListener(new CierraVentana());
       setLocationRelativeTo(null);
       setVisible(true);
    }

    public void actionPerformed(ActionEvent e) {
        String valor = e.getActionCommand();
        resolucionNueva(valor);
        resolucionActual = valor;
    }

    public String resolucionNueva(String reso) {
        System.out.println(reso);
        return reso;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElegirResolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElegirResolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElegirResolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElegirResolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElegirResolucion().setVisible(true);
            }
        });
    }

    class CierraVentana extends WindowAdapter {

        public void windowClosing(WindowEvent e) {
            dispose();
            System.exit(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
